### ISSUE TITLE
Soutien

### ISSUE THREAD

**Issue by svngoku** [Ckimnay/Semaine-d-intro_day-3---Mettre-en-ligne-page-d-accueil-google#1]
Hey, est-il possible de contribuer  ?

**Comment by Ckimnay** [comment]
Hey, Tu veux m'aider à corriger ma page d'accueil google?

**Comment by svngoku** [comment]
Oui oui

**Comment by svngoku** [comment]
Tu peux me rajouter comme contributeur afin de te partager ma correction ?

Merciii
